// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnywjsynbdafccljvmoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ueXdqc3luYmRhZmNjbGp2bW96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNjk1NTgsImV4cCI6MjA2NjY0NTU1OH0.eynouo4Ye6BdahKrU5Vn9zN2ONvTrdB5E0Y8-wToOBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);